# Generated by Django 5.2.3 on 2025-07-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historytracker',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='historytracker',
            old_name='ecpense_type',
            new_name='expense_type',
        ),
    ]
