# Generated by Django 5.2.3 on 2025-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_discription_historytracker_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historytracker',
            old_name='CurrentBalance',
            new_name='current_balance',
        ),
        migrations.AlterField(
            model_name='historytracker',
            name='expense_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=200),
        ),
    ]
