# Generated by Django 5.2.3 on 2025-07-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_requestlogs_request_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogs',
            name='request_info',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='requestlogs',
            name='request_method',
            field=models.CharField(max_length=2048),
        ),
    ]
