# Generated by Django 5.2.3 on 2025-07-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_requestlogs_request_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogs',
            name='request_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requestlogs',
            name='request_method',
            field=models.CharField(max_length=100),
        ),
    ]
